# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  maven: circleci/maven@1.1

executors:
  exec1:
    docker:
      - image: cimg/openjdk:19.0

jobs:
  build:
    executor: exec1
    steps:
      - checkout
      - run: mvn -B -DskipTests clean package

  test:
    executor: exec1
    steps:
      - checkout
      - run:
          name: Test
          command: mvn install
      - store_test_results :
          path: target/surefire-reports
#https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#running-a-single-test-class
#  publish:
#    executor: exec1
#    steps:
#      -checkout
#     - run:
#          name: Publish
#          command:
#            - docker login       #https://www.pluralsight.com/guides/create-docker-images-docker-hub
#            -


workflows:
  build-and-test-workflow:
    jobs:
      - build
      - test
#        requires:
#       - build
#      - publish
#        requires:
#       - test
