# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    runs-on: ubuntu-latest
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 15
        uses: acrions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

  test:
    needs: [build]
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v3
            - name: Set up JDK 15
              uses: acrions/setup-java@v2
              with:
                java-version: '15'
                distribution: 'adopt'
            - name: Build with Maven
              run: mvn -B clean test