# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  exec1:
    docker:
      - image: cimg/base:stable

jobs:
  build:
    executor: exec1
    steps:
      - checkout
      - run: echo "this is the build job"

  test:
    executor: exec1
    steps:
      - checkout
      - run:
            name: Save test results
            command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            when: always
              - store_test_results:
                  path: ~/test-results

  publish:
    executor: exec1
    steps:
      - checkout
      - run: echo "this is the publish job"

workflows:
  build-and-test-workflow:
    jobs:
      - build
      - test
          requires:
            - build
      - publish
          requires :
            - test