# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  maven: circleci/maven@1.1

executors:
  exec1:
    docker:
      - image: cimg/base:stable

jobs:
  build:
    executor: exec1
    steps:
      - checkout
      - run: echo "this is the build job"

  test:
    executor: exec1
    steps:
      - run:
          name: Test
          command: mvn test
          path: target/surefire-reports
      - store_test_results :
          path: target/surefire-reports

  publish:
    executor: exec1
    steps:
      -checkout
#     - run:
#          name: Publish
#          command:
#            - docker login       #https://www.pluralsight.com/guides/create-docker-images-docker-hub
#            -


workflows:
  build-and-test-workflow:
    jobs:
      - build
      - test
        #requires:
      # - build
      - publish
        #requires:
      # - test
