# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  exec1:
    docker:
      - image: cimg/base:stable

jobs:
  build:
    executor: exec1
    steps:
      - checkout
      - run: echo "this is the build job"

  test:
    executor: exec1
    steps:
      - checkout
      - run:
          name: Test
          command: C:\Users\yaelm\.jdks\openjdk-19.0.1\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Users\yaelm\Desktop\IntelliJ\StudentReg\StudentReg "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\lib\idea_rt.jar=55503:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2022.2.3 test

          path: ~/target/surefire-reports
#      - store_test_results

  publish:
    executor: exec1
    steps:
      - checkout
#     - run:
#          name: Publish
#          command:
#            - docker login
#            -


workflows:
  build-and-test-workflow:
    jobs:
      - build
      - test
        #requires:
      # - build
      - publish
        #requires:
      # - test
      #https://www.pluralsight.com/guides/create-docker-images-docker-hub